
import os

def generate_structure():
    # Helper to format SQL values
    def esc(text):
        return f"'{text.replace("'", "''")}'"

    sql_output = []
    
    sql_output.append("-- Migration: Seed Reading Plans Data (Full)")
    sql_output.append("-- Generated by Agent")
    sql_output.append("")
    sql_output.append("DO $$")
    sql_output.append("DECLARE")
    sql_output.append("    v_plano_1ano uuid;")
    sql_output.append("    v_plano_nt uuid;")
    sql_output.append("    v_plano_sp uuid;")
    sql_output.append("    v_plano_ev uuid;")
    sql_output.append("BEGIN")
    sql_output.append("    -- Get IDs")
    sql_output.append("    SELECT id INTO v_plano_1ano FROM public.planos WHERE titulo = 'Bíblia em 1 Ano';")
    sql_output.append("    SELECT id INTO v_plano_nt FROM public.planos WHERE titulo = 'Novo Testamento em 90 Dias';")
    sql_output.append("    SELECT id INTO v_plano_sp FROM public.planos WHERE titulo = 'Salmos e Provérbios';")
    sql_output.append("    SELECT id INTO v_plano_ev FROM public.planos WHERE titulo = 'Evangelhos em 30 Dias';")
    sql_output.append("")
    sql_output.append("    -- Clear existing days to avoid duplicates/conflicts")
    sql_output.append("    DELETE FROM public.plano_dias WHERE plano_id IN (v_plano_1ano, v_plano_nt, v_plano_sp, v_plano_ev);")
    sql_output.append("")

    # Better generator approach
    def get_ranges(books, days):
        # Flatten all chapters: [("Mateus", 1), ("Mateus", 2), ...]
        all_chapters = []
        for book, count in books:
            for c in range(1, count + 1):
                all_chapters.append(f"{book} {c}")
        
        # Distribute
        per_day = len(all_chapters) / days
        
        plan_days = []
        cursor = 0.0
        
        for d in range(1, days + 1):
            start_idx = int(cursor)
            cursor += per_day
            end_idx = int(cursor)
            
            # Ensure we reach the end on last day
            if d == days:
                end_idx = len(all_chapters)
            
            day_chaps = all_chapters[start_idx:end_idx]
            if not day_chaps: continue
            
            # Group by book
            grouped = {}
            for ch in day_chaps:
                # Fix for books with spaces: split from right, max 1 split
                b, c = ch.rsplit(" ", 1)
                if b not in grouped: grouped[b] = []
                grouped[b].append(int(c))
                
            ref_parts = []
            title_parts = []
            
            for b, chs in grouped.items():
                start, end = min(chs), max(chs)
                if start == end:
                    ref_parts.append(f"{b} {start}")
                else:
                    ref_parts.append(f"{b} {start}-{end}")
                title_parts.append(b)
            
            ref_str = "; ".join(ref_parts)
            title_str = f"Leitura de {', '.join(set(title_parts))}"
            
            plan_days.append((d, ref_str, title_str))
        
        return plan_days

    # 1. Evangelhos (30 Dias)
    evangelhos_books = [("Mateus", 28), ("Marcos", 16), ("Lucas", 24), ("João", 21)]
    days_ev = get_ranges(evangelhos_books, 30)
    
    sql_output.append("    -- Evangelhos em 30 Dias --")
    for d, ref, title in days_ev:
        sql_output.append(f"    INSERT INTO public.plano_dias (plano_id, dia_numero, referencia, titulo_dia) VALUES (v_plano_ev, {d}, {esc(ref)}, {esc(title)});")

    sql_output.append("")
    sql_output.append("    -- NT em 90 Dias --")
    
    nt_books = [
        ("Mateus", 28), ("Marcos", 16), ("Lucas", 24), ("João", 21),
        ("Atos", 28), ("Romanos", 16), ("1 Coríntios", 16), ("2 Coríntios", 13),
        ("Gálatas", 6), ("Efésios", 6), ("Filipenses", 4), ("Colossenses", 4),
        ("1 Tessalonicenses", 5), ("2 Tessalonicenses", 3), ("1 Timóteo", 6),
        ("2 Timóteo", 4), ("Tito", 3), ("Filemom", 1), ("Hebreus", 13),
        ("Tiago", 5), ("1 Pedro", 5), ("2 Pedro", 3), ("1 João", 5),
        ("2 João", 1), ("3 João", 1), ("Judas", 1), ("Apocalipse", 22)
    ]
    days_nt = get_ranges(nt_books, 90)
    
    for d, ref, title in days_nt:
        sql_output.append(f"    INSERT INTO public.plano_dias (plano_id, dia_numero, referencia, titulo_dia) VALUES (v_plano_nt, {d}, {esc(ref)}, {esc(title)});")
        
    sql_output.append("")
    sql_output.append("    -- Salmos e Provérbios (31 Dias) --")
    # 150 Psalms (5/day) + 31 Proverbs (1/day)
    # We will mix them: 5 Psalms then 1 Proverb per day is a classic pattern
    
    for d in range(1, 32):
        psalm_start = (d - 1) * 5 + 1
        psalm_end = min(d * 5, 150)
        
        prov_chap = d
        if prov_chap > 31: prov_chap = 31 # Cap invalid? Should fit exactly.
        
        ref = f"Salmos {psalm_start}-{psalm_end}; Provérbios {prov_chap}"
        title = f"Dia {d}: Sabedoria e Louvor"
        
        if psalm_start > 150: # Overflow check
             ref = f"Provérbios {prov_chap}"
        
        sql_output.append(f"    INSERT INTO public.plano_dias (plano_id, dia_numero, referencia, titulo_dia) VALUES (v_plano_sp, {d}, {esc(ref)}, {esc(title)});")

    sql_output.append("")
    sql_output.append("    -- Bíblia em 1 Ano (365 Dias) --")
    # Full simplistic list
    bible_books = [
        ("Gênesis", 50), ("Êxodo", 40), ("Levítico", 27), ("Números", 36), ("Deuteronômio", 34),
        ("Josué", 24), ("Juízes", 21), ("Rute", 4), ("1 Samuel", 31), ("2 Samuel", 24),
        ("1 Reis", 22), ("2 Reis", 25), ("1 Crônicas", 29), ("2 Crônicas", 36),
        ("Esdras", 10), ("Neemias", 13), ("Ester", 10), ("Jó", 42), ("Salmos", 150),
        ("Provérbios", 31), ("Eclesiastes", 12), ("Cânticos", 8), ("Isaías", 66),
        ("Jeremias", 52), ("Lamentações", 5), ("Ezequiel", 48), ("Daniel", 12),
        ("Oseias", 14), ("Joel", 3), ("Amós", 9), ("Obadias", 1), ("Jonas", 4),
        ("Miqueias", 7), ("Naum", 3), ("Habacuque", 3), ("Sofonias", 3), ("Ageu", 2),
        ("Zacarias", 14), ("Malaquias", 4),
        # NT
        ("Mateus", 28), ("Marcos", 16), ("Lucas", 24), ("João", 21),
        ("Atos", 28), ("Romanos", 16), ("1 Coríntios", 16), ("2 Coríntios", 13),
        ("Gálatas", 6), ("Efésios", 6), ("Filipenses", 4), ("Colossenses", 4),
        ("1 Tessalonicenses", 5), ("2 Tessalonicenses", 3), ("1 Timóteo", 6),
        ("2 Timóteo", 4), ("Tito", 3), ("Filemom", 1), ("Hebreus", 13),
        ("Tiago", 5), ("1 Pedro", 5), ("2 Pedro", 3), ("1 João", 5),
        ("2 João", 1), ("3 João", 1), ("Judas", 1), ("Apocalipse", 22)
    ]
    
    days_1ano = get_ranges(bible_books, 365)
    
    for d, ref, title in days_1ano:
        sql_output.append(f"    INSERT INTO public.plano_dias (plano_id, dia_numero, referencia, titulo_dia) VALUES (v_plano_1ano, {d}, {esc(ref)}, {esc(title)});")

    sql_output.append("END $$;")
    
    return "\n".join(sql_output)

if __name__ == "__main__":
    content = generate_structure()
    with open("supabase/migrations/20260215_seed_reading_plans.sql", "w", encoding="utf-8") as f:
        f.write(content)
    print("Migration file created: supabase/migrations/20260215_seed_reading_plans.sql")
