-- Tabela para guardar inscrições de push notification
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  subscription_json jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Evitar duplicatas exatas
  constraint push_subscriptions_unique unique(subscription_json)
);

-- RLS: Permitir que qualquer um insira (anonKey) pois não temos auth obrigatória
alter table public.push_subscriptions enable row level security;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable insert for everyone' AND tablename = 'push_subscriptions') THEN
    CREATE POLICY "Enable insert for everyone" ON public.push_subscriptions FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable read for service role only' AND tablename = 'push_subscriptions') THEN
    CREATE POLICY "Enable read for service role only" ON public.push_subscriptions FOR SELECT USING (auth.role() = 'service_role');
  END IF;
END $$;
