-- Tabela para guardar inscrições de push notification
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  subscription_json jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Evitar duplicatas exatas
  constraint push_subscriptions_unique unique(subscription_json)
);

-- RLS: Permitir que qualquer um insira (anonKey) pois não temos auth obrigatória
alter table public.push_subscriptions enable row level security;

create policy "Enable insert for everyone" 
on public.push_subscriptions for insert 
with check (true);

create policy "Enable read for service role only" 
on public.push_subscriptions for select 
using (auth.role() = 'service_role');
